 stardusthotel/Stardust/Stardust/Models/Administracion/TipoHabitacion/TipoHabitacionBean.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace Stardust.Models
{
    public class TipoHabitacionBean
    {
        [Key]
        public int ID { get; set; }

        [Display( Name = "Tipo de Habitación" ) ]
        [Required( ErrorMessage = "Ingrese un nombre para el tipo de habitación" ) ]
        public String nombre { get; set; }

        [Display( Name = "Descripción" ) ]
        [Required(ErrorMessage = "Ingrese una descripción para el tipo de habitación")]
        public String descripcion { get; set; }
    }
}

 stardusthotel/Stardust/Stardust/Models/Administracion/TipoHabitacion/TipoHabitacionDAO.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Configuration;
using System.Data.SqlClient;
using log4net;
using System.Web.Configuration;

namespace Stardust.Models
{
    public class TipoHabitacionDAO
    {
        String cadenaDB = WebConfigurationManager.ConnectionStrings["CadenaHotelDB"].ConnectionString;
        private static ILog log = LogManager.GetLogger(typeof(TipoHabitacionDAO));

        public TipoHabitacionBean getTipoHabitacion(int id) {
            SqlConnection objDB = null;

            try
            {
                objDB = new SqlConnection(cadenaDB);
                TipoHabitacionBean tipoHabitacion = null;

                objDB.Open();
                String strQuery = "SELECT * FROM TipoHabitacion WHERE idTipoHabitacion = @idTipoHabitacion";
                SqlCommand objQuery = new SqlCommand(strQuery, objDB);
                DAO.agregarParametro(objQuery, "idTipoHabitacion", id);

                SqlDataReader objDataReader = objQuery.ExecuteReader();

                if (objDataReader.HasRows)
                {
                    objDataReader.Read();
                    tipoHabitacion = new TipoHabitacionBean();

                    tipoHabitacion.ID = Convert.ToInt32(objDataReader["idTipoHabitacion"]);
                    tipoHabitacion.nombre = Convert.ToString(objDataReader["nombre"]);
                    tipoHabitacion.descripcion = Convert.ToString(objDataReader["descripcion"]);
                }

                return tipoHabitacion;
            }
            catch (Exception e)
            {
                log.Error("getTipoHabitacion(EXCEPTION): " + e);
                throw e;
            }
            finally
            {
                if (objDB != null)
                {
                    objDB.Close();
                }
            }
        }

        public IEnumerable<TipoHabitacionBean> getTipoHabitacionXHotel(int idHotel)
        {
            SqlConnection objDB = null;

            try
            {
                objDB = new SqlConnection(cadenaDB);
                List<TipoHabitacionBean> listaTipoHabitacion = new List<TipoHabitacionBean>();

                objDB.Open();
                String strQuery = "SELECT A.* " +
                                    "FROM TipoHabitacion A, TipoHabitacionXHotel B " +
                                    "WHERE A.idTipoHabitacion = B.idTipoHabitacion and B.idHotel = @idHotel";
                SqlCommand objQuery = new SqlCommand(strQuery, objDB);
                DAO.agregarParametro(objQuery, "idHotel", idHotel);

                SqlDataReader objDataReader = objQuery.ExecuteReader();
                if (objDataReader.HasRows)
                {
                    while (objDataReader.Read())
                    {
                        TipoHabitacionBean tipoHabitacion = new TipoHabitacionBean();

                        tipoHabitacion.ID = Convert.ToInt32(objDataReader["idTipoHabitacion"]);
                        tipoHabitacion.nombre = Convert.ToString(objDataReader["nombre"]);
                        tipoHabitacion.descripcion = Convert.ToString(objDataReader["descripcion"]);

                        listaTipoHabitacion.Add(tipoHabitacion);
                    }
                }
                // en caso de no leer tipos de habitaciones, devolverla una lista vacia
                return listaTipoHabitacion;
            }
            catch (Exception e) {
                log.Error("getTipoHabitacionXHotel(EXCEPTION): " + e);
                throw (e);
            }
            finally
            {
                if (objDB != null)
                {
                    objDB.Close();
                }
            }
        }

        public void registrarTipoHabitacion(TipoHabitacionBean tipo) {
            SqlConnection sql = null;

            try
            {
                sql = new SqlConnection(cadenaDB);

                sql.Open();

                String command = "Insert into TipoHabitacion ( nombre , descripcion ) values ('" +
                                    tipo.nombre + "', '" +
                                    tipo.descripcion + "')";

                SqlCommand query = new SqlCommand(command, sql);

                query.ExecuteNonQuery();

                sql.Close();
            }
            catch (Exception e) {
                log.Error("registrarTipoHabitacion(EXCEPTION): " + e);
            }
            finally {
                if (sql != null) sql.Close();
            }
        }

        public void actualizarTipoHabitacion(TipoHabitacionBean tipo) {
            SqlConnection sql = null;

            try
            {
                sql = new SqlConnection(cadenaDB);

                sql.Open();

                String command = "Update TipoHabitacion SET " +
                                    "nombre = '" + tipo.nombre + "', " +
                                    "descripcion = '" + tipo.descripcion + "' " +
                                    "where idTipoHabitacion = " + tipo.ID;
                SqlCommand query = new SqlCommand(command, sql);

                query.ExecuteNonQuery();

                sql.Close();
            }
            catch (Exception e) {
                log.Error("actualizarTipoHabitacion(EXCEPTION): " + e);               
            }
            finally {
                if (sql != null) sql.Close();
            }
        }

        public void eliminarTipoHabitacion(int id) {
            SqlConnection sql = null;

            try
            {
                sql = new SqlConnection(cadenaDB);

                sql.Open();

                String command = "Delete from TipoHabitacion where idTipoHabitacion = " + id;

                SqlCommand query = new SqlCommand(command, sql);

                query.ExecuteNonQuery();

                sql.Close();
            }
            catch (Exception e) {
                log.Error("eliminarTipoHabitacion(EXCEPTION): " + e);
            }
            finally {
                if (sql != null) sql.Close();
            }
        }

        public List<TipoHabitacionBean> listarTipoHabitacion() {
            SqlConnection sql = null;
            try
            {
                sql = new SqlConnection(cadenaDB);

                sql.Open();

                String command = "Select * from TipoHabitacion";
                SqlCommand query = new SqlCommand(command, sql);

                SqlDataReader data = query.ExecuteReader();

                List<TipoHabitacionBean> lista = new List<TipoHabitacionBean>();

                while (data.Read())
                {
                    TipoHabitacionBean tipo = new TipoHabitacionBean();

                    tipo.ID = (int)data.GetValue(0);
                    tipo.nombre = (string)data.GetValue(1);
                    tipo.descripcion = (string)data.GetValue(2);

                    lista.Add(tipo);
                }

                sql.Close();

                return lista;
            }
            catch (Exception e) {
                log.Error("listarTipoHabitacion(EXCEPTION): " + e);
                throw (e);
            }
            finally {
                if (sql != null) sql.Close();
            }
        }
    }
}

 stardusthotel/Stardust/Stardust/Models/Administracion/TipoHabitacion/TipoHabitacionFacade.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Stardust.Models
{
    public class TipoHabitacionFacade
    {
        TipoHabitacionService tipoServ = new TipoHabitacionService();
        
        public TipoHabitacionBean getTipoHabitacion(int id) {
            return tipoServ.getTipoHabitacion(id);
        }

        public IEnumerable<TipoHabitacionBean> getTipoHabitacionXHotel(int idHotel)
        {
            return tipoServ.getTipoHabitacionXHotel(idHotel);
        }

        public void registrarTipoHabitacion(TipoHabitacionBean tipo) {
            tipoServ.registrarTipoHabitacion(tipo);
        }

        public void actualizarTipoHabitacion(TipoHabitacionBean tipo) {
            tipoServ.actualizarTipoHabitacion(tipo);
        }

        public void eliminarTipoHabitacion( int id ) {
            tipoServ.eliminarTipoHabitacion( id );
        }

        public List<TipoHabitacionBean> listarTipoHabitacion() {
            return tipoServ.listarTipoHabitacion();
        }
    }
}

 stardusthotel/Stardust/Stardust/Models/Administracion/TipoHabitacion/TipoHabitacionService.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Stardust.Models
{
    public class TipoHabitacionService
    {
        TipoHabitacionDAO tipoDAO = new TipoHabitacionDAO();

        public TipoHabitacionBean getTipoHabitacion(int id)
        {
            return tipoDAO.getTipoHabitacion(id);
        }

        public IEnumerable<TipoHabitacionBean> getTipoHabitacionXHotel(int idHotel)
        {
            return tipoDAO.getTipoHabitacionXHotel(idHotel);
        }

        public void registrarTipoHabitacion(TipoHabitacionBean tipo) {
            tipoDAO.registrarTipoHabitacion(tipo);
        }

        public void actualizarTipoHabitacion(TipoHabitacionBean tipo) {
            tipoDAO.actualizarTipoHabitacion(tipo);
        }

        public void eliminarTipoHabitacion( int id ) {
            tipoDAO.eliminarTipoHabitacion( id );
        }

        public List<TipoHabitacionBean> listarTipoHabitacion() {
            return tipoDAO.listarTipoHabitacion();
        }
    }
}

 stardusthotel/Stardust/Stardust/Controllers/Administracion/TipoHabitacionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Stardust.Models;

namespace Stardust.Controllers
{ 
    public class TipoHabitacionController : Controller
    {
        private CadenaHotelDB db = new CadenaHotelDB();
        TipoHabitacionFacade tipoFac = new TipoHabitacionFacade();

        //
        // GET: /TipoHabitacion/

        public ViewResult Index()
        {
            return View();
        }

        //
        // GET: /TipoHabitacion/Details/5

        public ViewResult Details(int id)
        {
            try
            {
                return View(tipoFac.getTipoHabitacion(id));
            }
            catch {
                ViewBag.results = "Ocurrió un error al intentar cargar el tipo de habitación";
                return View(new TipoHabitacionBean());
            }
        }

        //
        // GET: /TipoHabitacion/Create

        public ActionResult Create()
        {
            return View();
        } 

        //
        // POST: /TipoHabitacion/Create

        [HttpPost]
        public ActionResult Create(TipoHabitacionBean tipohabitacion)
        {
            try
            {
                tipoFac.registrarTipoHabitacion(tipohabitacion);

                return RedirectToAction("List");
            }
            catch {
                ViewBag.results = "Ocurrió un error al intentar crear el tipo de habitación";
                return View(new TipoHabitacionBean());
            }
        }
        
        //
        // GET: /TipoHabitacion/Edit/5
 
        public ActionResult Edit(int id)
        {
            try
            {
                return View(tipoFac.getTipoHabitacion(id));
            }
            catch {
                ViewBag.results = "Ocurrió un error al intentar cargar el tipo de habitación";
                return View(new TipoHabitacionBean());
            }
        }

        //
        // POST: /TipoHabitacion/Edit/5

        [HttpPost]
        public ActionResult Edit(TipoHabitacionBean tipohabitacion)
        {
            try
            {
                tipoFac.actualizarTipoHabitacion(tipohabitacion);
                return RedirectToAction("List");
            }
            catch {
                ViewBag.results = "Ocurrió un error al intentar modificar el tipo de habitación";
                return View(new TipoHabitacionBean());
            }
        }

        //
        // GET: /TipoHabitacion/Delete/5
 
        public ActionResult Delete(int id)
        {
            try
            {
                return View(tipoFac.getTipoHabitacion(id));
            }
            catch {
                ViewBag.results = "Ocurrió un error al intentar cargar el tipo de habitación";
                return View(new TipoHabitacionBean());
            }
        }

        //
        // POST: /TipoHabitacion/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                tipoFac.eliminarTipoHabitacion(id);
                return RedirectToAction("List");
            }
            catch
            {
                ViewBag.results = "Ocurrió un error al intentar eliminar el tipo de habitación";
                return View(new TipoHabitacionBean());
            }
        }

        //[HttpPost, ActionName("Delete")]
        //public JsonResult DeleteConfirmed(int id) {
        //    try
        //    {
        //        tipoFac.eliminarTipoHabitacion(id);
        //        return Json(new { me = "" });
        //    }catch{
        //        return Json(new { me = "GG!" });
        //    }
        //}

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }

        public ActionResult List()
        {
            try
            {
                var model = tipoFac.listarTipoHabitacion();
                return View(model);
            }
            catch {
                ViewBag.results = "Ocurrió un error al intentar listar los tipo de habitación";
                return View(new List<TipoHabitacionBean>());
            }
        }
    }
}

 stardusthotel/Stardust/Stardust/Views/TipoHabitacion/Create.cshtml
@model Stardust.Models.TipoHabitacionBean

@{
    ViewBag.Title = "Crear tipo de habitación";
}

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validationEngine-en.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validationEngine.js")" type="text/javascript"></script>

@if (!String.IsNullOrEmpty(ViewBag.results)) { 
    <div class="nNote nWarning hideit">
        <p><strong>AVISO: </strong>@ViewBag.results</p>
    </div>
}

@using (Html.BeginForm("Create", "TipoHabitacion", FormMethod.Post, new { @class = "form", id = "validate" }))
{
    @Html.ValidationSummary(true)
    <fieldset>
        <div class = "widget" >
            <div class = "title"><h6>Crear tipo de habitación</h6></div>

            <div class="formRow">
                @Html.LabelFor(model => model.nombre )<span class="req">*</span>
                <div class = "formRight" >
                    @Html.TextBoxFor(model => model.nombre, new { @class = "validate[required,custom[onlyLetterSp]]", name = "lettersValid", maxlength = "30", placeholder = "Maximo 30 caracteres aqui" })
                    @Html.ValidationMessageFor( model => model.nombre )
                </div>
                <div class = "clear" ></div>
            </div>

            <div class="formRow">
                @Html.LabelFor(model => model.descripcion )
                <div class = "formRight" >
                    @Html.TextAreaFor(model => model.descripcion )
                    @Html.ValidationMessageFor( model => model.descripcion )
                </div>
                
                <div class = "clear" ></div>
            </div>

        </div>
    </fieldset>
    <p>
        <input type="submit" value="Crear" class = "redB" />
    </p>
}


<div>
    @Html.ActionLink("Regresar", "List")
</div>

 stardusthotel/Stardust/Stardust/Views/TipoHabitacion/Delete.cshtml
@model Stardust.Models.TipoHabitacionBean

@{
    ViewBag.Title = "Borrar tipo de habitación";
}

@if (!String.IsNullOrEmpty(ViewBag.results)) { 
    <div class="nNote nWarning hideit">
        <p><strong>AVISO: </strong>@ViewBag.results</p>
    </div>
}

<h3>Seguro de querer eliminar este tipo de habitación?</h3>

<fieldset>
    <div class = "widget" >
        <div class = "title"><h6>Detalles del Usuario</h6></div>
    @*<legend>Usuario</legend>*@

        <div class="formRow">
            @Html.LabelFor(model => model.nombre )
            <div class = "formRight" >@Html.DisplayFor(model => model.nombre )</div>
            <div class = "clear" ></div>
        </div>

        <div class="formRow">
            @Html.LabelFor(model => model.descripcion )
            <div class = "formRight" >@Html.DisplayFor(model => model.descripcion )</div>
            <div class = "clear" ></div>
        </div>

    </div>
</fieldset>

@using (Html.BeginForm("Delete", "TipoHabitacion", FormMethod.Post, new { @class = "form" } ))
{
    <p>
        <input type="submit" value="Borrar" class = "redB"/> |
        @Html.ActionLink("Regresar", "List")
    </p>
}

 stardusthotel/Stardust/Stardust/Views/TipoHabitacion/Details.cshtml
@model Stardust.Models.TipoHabitacionBean

@{
    ViewBag.Title = "Detalles del tipo de habitación";
}

@if (!String.IsNullOrEmpty(ViewBag.results)) { 
    <div class="nNote nWarning hideit">
        <p><strong>AVISO: </strong>@ViewBag.results</p>
    </div>
}

<h2>Detalle</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm("Details", "TipoHabitacion", FormMethod.Post, new { @class = "form" }))
{
    @Html.ValidationSummary(true)
    <fieldset>
        <div class = "widget" >
            <div class = "title"><h6>Detalles del tipo de habitación</h6></div>

            <div class="formRow">
                @Html.LabelFor(model => model.nombre)
                <div class = "formRight" >@Html.DisplayFor(model => model.nombre)</div>
                <div class = "clear" ></div>
            </div>

            <div class="formRow">
                @Html.LabelFor(model => model.descripcion)
                <div class = "formRight" >@Html.DisplayFor(model => model.descripcion)</div>
                <div class = "clear" ></div>
            </div>

        </div>
    </fieldset>
    <p>
        <a href="@Url.Action("Edit", new { id = Model.ID })"><img src="../../Content/images/icons/color/pencil.png", alt="Edit" />Editar</a> | 
        @Html.ActionLink("Regresar", "List")
    </p>
}

 stardusthotel/Stardust/Stardust/Views/TipoHabitacion/Edit.cshtml
@model Stardust.Models.TipoHabitacionBean

@{
    ViewBag.Title = "Modificar tipo de habitación";
}

@if (!String.IsNullOrEmpty(ViewBag.results)) { 
    <div class="nNote nWarning hideit">
        <p><strong>AVISO: </strong>@ViewBag.results</p>
    </div>
}

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm( "Edit" , "TipoHabitacion" , FormMethod.Post , new { @class = "form", id = "validate" } ) ){
    @Html.ValidationSummary(true)
    <fieldset>
        <div class = "widget" >
            <div class = "title"><h6>Modificar tipo de habitación</h6></div>

            <div class="formRow">
                @Html.LabelFor(model => model.nombre)<span class="req">*</span>
                <div class = "formRight" >
                    @Html.TextBoxFor(model => model.nombre, new { @class = "validate[required,custom[onlyLetterSp]]", name = "lettersValid", maxlength = "30" })
                    @Html.ValidationMessageFor( model => model.nombre )
                </div>
                <div class = "clear" ></div>
            </div>

            <div class="formRow">
                @Html.LabelFor(model => model.descripcion )
                <div class = "formRight" >
                    @Html.TextAreaFor(model => model.descripcion )
                    @Html.ValidationMessageFor( model => model.descripcion )
                </div>
                <div class = "clear" ></div>
            </div>
            
        </div>
    </fieldset>
    <p>
        <input type="submit" value="Guardar" class = "redB" />
    </p>
}


<div>
    @Html.ActionLink("Regresar", "Index")
</div>

 stardusthotel/Stardust/Stardust/Views/TipoHabitacion/Index.cshtml
@model IEnumerable<Stardust.Models.TipoHabitacionBean>

@{
    ViewBag.Title = "Tipos de habitación";
}

<h2>Tipos de Habitación</h2>

<p>
    Bienvenido a administrar tipos de habitación.
</p>

<p>
    @Html.ActionLink("Registrar tipo de habitación", "Create")
</p>

<p>
    @Html.ActionLink("Listar tipos de habitación", "List")
</p>

 stardusthotel/Stardust/Stardust/Views/TipoHabitacion/List.cshtml
@model IEnumerable<Stardust.Models.TipoHabitacionBean>

@{
    ViewBag.Title = "Tipos de habitación";
}

@if (!String.IsNullOrEmpty(ViewBag.results)) { 
    <div class="nNote nWarning hideit">
        <p><strong>AVISO: </strong>@ViewBag.results</p>
    </div>
}

<h2>Tipos de habitación</h2>

<p>
    <a href="@Url.Action("Create")"><img src="@Url.Content("~/Content/images/icons/color/plus.png")" alt="Create" />Añadir tipo de habitación</a>
</p>

<div class="wrapper">
    <div class="widget">
        <div class="title"><h6>Tipos de habitación</h6></div>
        <div class="dataTables_wrapper">
            <table cellpadding = "0" cellspacing = "0" width = "100%" class = "display dTable">
                <thead>
                    <tr>
                        <th class="ui-state-default" rowspan="1" colspan="1" style="width:170px;" >
                            <div class="DataTables_sort_wrapper">
                            Nombre
                            <span class="DataTables_sort_icon css_right ui-icon ui-icon-triangle-1-s"></span>
                            </div>
                        </th>
                        <th class="ui-state-default" rowspan="1" colspan="1" style="width:170px;" >
                            <div class="DataTables_sort_wrapper">
                            Descripción
                            <span class="DataTables_sort_icon css_right ui-icon ui-icon-triangle-1-s"></span>
                            </div>
                        </th>
                        <th class="ui-state-default" rowspan="1" colspan="1" style="width:170px;" >
                            <div class="DataTables_sort_wrapper">
                            Opciones
                            <span class="DataTables_sort_icon css_right ui-icon ui-icon-triangle-1-s"></span>
                            </div>
                        </th>
                </thead>
                <tbody>
                @foreach (var item in Model) {
                    <tr class="gradeA odd">
                        <td>@Html.DisplayFor(modelItem => item.nombre )</td>
                        <td>@Html.DisplayFor(modelItem => item.descripcion )</td>
                        <td>
                            <a href="@Url.Action("Edit", new { id = item.ID })"><img src="@Url.Content("~/Content/images/icons/color/pencil.png")" alt="Edit" />Editar </a> | 
                            <a href="@Url.Action("Details", new { id = item.ID })"><img src="@Url.Content("~/Content/images/icons/color/edit-column.png")" alt="Details" />Detalles</a> | 
                            <a id = @item.ID class = "eliminar" href = "" ><img src="@Url.Content("~/Content/images/icons/color/cross.png")" alt="Delete" />Borrar</a>
                        </td>
                    </tr>        
                }
                </tbody>
            </table>
        </div>
    </div>
</div>