 stardusthotel/Stardust/Stardust/Models/Compras y Ventas/Pago/ListaHabitacion.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Stardust.Models
{
    public class ListaHabitacionEstado
    {
        public int idReserva { get; set; }
        public string estado { get; set; }
    }
    public class ListaHabitacion
    {
        public int idHabit { get; set; }
        public string nHabit { get; set; }
        public List<ListaHabitacionEstado> listaFechas { get; set; }
        public ListaHabitacion()
        {
            listaFechas = new List<ListaHabitacionEstado>();
        }
    }
}

 stardusthotel/Stardust/Stardust/Models/Compras y Ventas/Pago/PagoAdelantadoBean.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Stardust.Models
{
    public class PagoAdelantadoBean
    {
        public string data { get; set; }
        public string doc { get; set; }
        public string nom { get; set; }
        public int estado { get; set; }
        public decimal montoInicial { get; set; }
        public string mensaje { get; set; }
        public decimal montoTotal { get; set; }
    }
}

 stardusthotel/Stardust/Stardust/Models/Compras y Ventas/Pago/PagoDAO.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Configuration;
using System.Data.SqlClient;
using Stardust.Models.Servicios;
using log4net;

namespace Stardust.Models
{
    public class PagoDAO
    {
        private static ILog log = LogManager.GetLogger(typeof (PagoDAO));
        public int GetID(string doc)
        {
            int id=0;

            try
            {
                String cadenaConfiguracion = ConfigurationManager.ConnectionStrings["CadenaHotelDB"].ConnectionString;

                SqlConnection sqlCon = new SqlConnection(cadenaConfiguracion);

                sqlCon.Open();

                string commandString = "SELECT * FROM Usuario WHERE nroDocumento = '" + doc + "'";

                SqlCommand sqlCmd = new SqlCommand(commandString, sqlCon);
                SqlDataReader dataReader = sqlCmd.ExecuteReader();

                if (dataReader.Read())
                {
                    id = (int)dataReader["idUsuario"];
                }

                sqlCon.Close();

                return id;
            }
            catch (Exception ex)
            {
                log.Error("getID(EXCEPTION): ", ex);
                throw ex;
            }
        }

        public ReservaCheckOut GetReserva2(int id)
        {
            try
            {
                ReservaCheckOut reserva = new ReservaCheckOut();

                String cadenaConfiguracion = ConfigurationManager.ConnectionStrings["CadenaHotelDB"].ConnectionString;

                SqlConnection sqlCon = new SqlConnection(cadenaConfiguracion);

                sqlCon.Open();

                string commandString = "SELECT * FROM Reserva WHERE estado = 4 AND idReserva = " + id;

                SqlCommand sqlCmd = new SqlCommand(commandString, sqlCon);
                SqlDataReader dataReader = sqlCmd.ExecuteReader();
                DateTime fechaIni = new DateTime();
                DateTime fechaHoy = DateTime.Now;

                if (dataReader.Read())
                {
                    reserva.id = (int)dataReader["idReserva"];
                    fechaIni = (DateTime)dataReader["fechaLlegada"];
                    reserva.fechaIni = fechaIni.ToString("dd-MM-yyyy");
                    reserva.fechaFin = ((DateTime)dataReader["fechaSalida"]).ToString("dd-MM-yyyy");
                    reserva.fechaHoy = fechaHoy.ToString("dd-MM-yyyy");
                    int idU = (int)dataReader["idUsuario"];
                    UsuarioBean usuario = GetNombreUsuario(idU);
                    reserva.tipoDoc = usuario.tipoDocumento;
                    reserva.dni = usuario.nroDocumento;
                    reserva.nombre = usuario.nombres;
                }

                dataReader.Close();

                if (fechaIni <= fechaHoy)
                {
                    commandString = "SELECT * FROM DocumentoPago WHERE idReserva = " + id;

                    SqlCommand sqlCmd2 = new SqlCommand(commandString, sqlCon);
                    SqlDataReader dataReader2 = sqlCmd2.ExecuteReader();

                    TimeSpan dias = fechaHoy - fechaIni;

                    int idDoc = 0;

                    if (dataReader2.Read())
                    {
                        reserva.faltante = (decimal)dataReader2["montoFaltante"];
                        reserva.idDocPago = (int)dataReader2["idDocPago"];
                        idDoc = (int)dataReader2["idDocPago"];
                    }

                    reserva.listaDetalles = ListaDetalle(idDoc, dias.Days + 1);

                    for (int i = 0; i < reserva.listaDetalles.Count; i++)
                        reserva.subTotal += reserva.listaDetalles.ElementAt(i).totalDet;

                    reserva.IGV = reserva.subTotal * 18 / 100;
                    reserva.total = reserva.IGV + reserva.subTotal;

                    reserva.montPagado = reserva.total - reserva.faltante;

                    sqlCon.Close();
                }

                return reserva;
            }
            catch (Exception ex)
            {
                log.Error("getreserva(EXCEPTION): ", ex);
                throw ex;
            }
        }

        public ReservaCheckOut GetReserva(int id)
        {
            try
            {
                ReservaCheckOut reserva = new ReservaCheckOut();

                String cadenaConfiguracion = ConfigurationManager.ConnectionStrings["CadenaHotelDB"].ConnectionString;

                SqlConnection sqlCon = new SqlConnection(cadenaConfiguracion);

                sqlCon.Open();

                string commandString = "SELECT * FROM Reserva WHERE estado = 3 AND idReserva = " + id;

                SqlCommand sqlCmd = new SqlCommand(commandString, sqlCon);
                SqlDataReader dataReader = sqlCmd.ExecuteReader();
                DateTime fechaIni = new DateTime();
                DateTime fechaHoy = DateTime.Now;

                if (dataReader.Read())
                {
                    reserva.id = (int)dataReader["idReserva"];
                    fechaIni = (DateTime)dataReader["fechaLlegada"];
                    reserva.fechaIni = fechaIni.ToString("dd-MM-yyyy");
                    reserva.fechaFin = ((DateTime)dataReader["fechaSalida"]).ToString("dd-MM-yyyy");
                    reserva.fechaHoy = fechaHoy.ToString("dd-MM-yyyy");
                    int idU = (int)dataReader["idUsuario"];
                    UsuarioBean usuario = GetNombreUsuario(idU);
                    reserva.tipoDoc = usuario.tipoDocumento;
                    reserva.dni = usuario.nroDocumento;
                    reserva.nombre = usuario.nombres;
                }

                dataReader.Close();

                if (fechaIni <= fechaHoy)
                {
                    commandString = "SELECT * FROM DocumentoPago WHERE idReserva = " + id;

                    SqlCommand sqlCmd2 = new SqlCommand(commandString, sqlCon);
                    SqlDataReader dataReader2 = sqlCmd2.ExecuteReader();

                    TimeSpan dias = fechaHoy - fechaIni;

                    int idDoc = 0;

                    decimal tot = 0;

                    if (dataReader2.Read())
                    {
                        reserva.faltante = (decimal)dataReader2["montoFaltante"];
                        reserva.idDocPago = (int)dataReader2["idDocPago"];
                        tot = (decimal)dataReader2["montoTotal"];
                        idDoc = (int)dataReader2["idDocPago"];
                    }

                    reserva.listaDetalles = ListaDetalle(idDoc, dias.Days + 1);

                    for (int i = 0; i < reserva.listaDetalles.Count; i++)
                        reserva.subTotal += reserva.listaDetalles.ElementAt(i).totalDet;

                    reserva.IGV = reserva.subTotal * 18 / 100;
                    reserva.total = reserva.IGV + reserva.subTotal;

                    decimal pagado = tot - reserva.faltante;
                    reserva.faltante = reserva.total - pagado;

                    reserva.montPagado = pagado;

                    sqlCon.Close();
                }

                return reserva;
            }
            catch (Exception ex)
            {
                log.Error("getreserva(EXCEPTION): ", ex);
                throw ex;
            }
        }

        public MensajeBean RegistrarCheckOut(int id)
        {
            MensajeBean mensaje = new MensajeBean();

            try
            {
                ReservaCheckOut reserva = GetReserva(id);

                String cadenaConfiguracion = ConfigurationManager.ConnectionStrings["CadenaHotelDB"].ConnectionString;

                SqlConnection sqlCon = new SqlConnection(cadenaConfiguracion);
                sqlCon.Open();

                decimal faltante = 0;

                string commandString = "UPDATE DocumentoPago SET montoTotal = " + reserva.total + " , montoFaltante = " + faltante + " , subTotal = " + reserva.subTotal + " , igv = " + reserva.IGV + " , estado = 3 WHERE idDocPago = " + reserva.idDocPago;

                SqlCommand sqlCmd = new SqlCommand(commandString, sqlCon);
                sqlCmd.ExecuteNonQuery();

                if (reserva.faltante > 0)
                {                    
                    commandString = "INSERT INTO Pagos VALUES ( " + reserva.faltante + " , NULL , GETDATE() , " + reserva.idDocPago;

                    if (reserva.tipoDoc.Equals("DNI"))
                        commandString += " , 'Boleta' )";
                    else
                        commandString += " , 'Factura' )";

                    SqlCommand sqlCmd2 = new SqlCommand(commandString, sqlCon);
                    sqlCmd2.ExecuteNonQuery();
                }

                commandString = "UPDATE Reserva SET estado = 4 , fechaCheckOut = GETDATE() WHERE idReserva = " + reserva.id;
                SqlCommand sqlCmd3 = new SqlCommand(commandString, sqlCon);
                sqlCmd3.ExecuteNonQuery();

                mensaje.me = ActualizarHabitacion(id);

                mensaje.me = ActualizarPagoDetalle(reserva.listaDetalles);

                mensaje.id = id;
                
                return mensaje;
            }
            catch (Exception e)
            {
                mensaje.me = e.ToString();
                log.Error("registrarcheckout(EXCEPTION): ", e);
                return mensaje;
            }           
        }

        public ReservaCheckOut GetEvento(int id)
        {
            try
            {
                ReservaCheckOut reserva = new ReservaCheckOut();


 stardusthotel/Stardust/Stardust/Models/Compras y Ventas/Pago/PagoService.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Stardust.Models.Servicios;

namespace Stardust.Models
{
    public class PagoService
    {
        PagoDAO pagoDAO = new PagoDAO();
        public ReservaCheckOut GetReserva(int id)
        {
            return pagoDAO.GetReserva(id);
        }

        public MensajeBean RegistrarCheckOut(int id)
        {
            return pagoDAO.RegistrarCheckOut(id);
        }

        public PagoAdelantadoBean PagoAdelantado(RequestPagoAde request)
        {
            return pagoDAO.PagoAdelantado(request);
        }

        public List<ListaHabitacion> listaHabitacion(int idHotel,string fechaIni, string fechaFin)
        {
            return pagoDAO.listaHabitacion(idHotel,fechaIni, fechaFin);
        }
    }
}

 stardusthotel/Stardust/Stardust/Models/Compras y Ventas/Pago/Request/RequestCheckOut.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Stardust.Models
{
    public class RequestCheckOut
    {
        public int idReserva { get; set; }
    }
}

 stardusthotel/Stardust/Stardust/Models/Compras y Ventas/Pago/Request/RequestPagoAde.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Stardust.Models
{
    public class RequestPagoAde
    {
        public int flag { get; set; }
        public int id { get; set; }
        public string doc { get; set; }
    }
}

 stardusthotel/Stardust/Stardust/Models/Compras y Ventas/Pago/Request/RequestRegPago.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Stardust.Models
{
    public class RequestRegPago
    {
        public int flag { get; set; }
        public int id { get; set; }
        public decimal monto { get; set; }
        public decimal montoTotal { get; set; }
        public decimal pagoInicial { get; set; }
        public string doc { get; set; }
    }
}

 stardusthotel/Stardust/Stardust/Models/Compras y Ventas/Pago/ReservaCheckOut.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.ComponentModel.DataAnnotations;

namespace Stardust.Models
{
    public class ReservaCheckOut
    {
        public int id { get; set; }
        public int idDocPago { get; set; }
        public decimal total { get; set; }
        public decimal subTotal { get; set; }
        public decimal IGV { get; set; }
        public decimal montPagado { get; set; }
        public decimal faltante { get; set; }
        public string fechaIni { get; set; }
        public string fechaFin { get; set; }
        public string fechaHoy { get; set; }
        public int idHotel { get; set; }
        public string nombre { get; set; }
        public string dni { get; set; }
        public string tipoDoc { get; set; }
        public int idUsuario { get; set; }
        public List<TipoDetalle> listaDetalles { get; set; }
        public ReservaCheckOut()
        {
            listaDetalles = new List<TipoDetalle>();
        }
    }

    public class TipoDetalle
    {
        public int id { get; set; }
        public int idDetalle { get; set; }
        public string detalle { get; set; }
        public int cantidad { get; set; }
        public decimal pUnit { get; set; }
        public decimal totalDet { get; set; }
        public int estado { get; set; }
    }
}

 stardusthotel/Stardust/Stardust/Controllers/Compras y Ventas/PagoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Stardust.Models;
using log4net;

namespace Stardust.Controllers
{
    public class PagoController : Controller
    {

        /*---------Pago de Servicios, Evento y ambientes------*/

        PagoFacade pagoFacade = new PagoFacade();
        private static ILog log = LogManager.GetLogger(typeof(PagoController));
        public ActionResult Buscar()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Buscar(string nombre)
        {
            return RedirectToAction("Listar", new { nom = nombre });
        }

        //public ActionResult Listar(string nom)
        //{
        //    List<ReservaBean> reserva = pagoFacade.GetReserva(nom);
        //    if (reserva.Count == 0)
        //        ViewBag.Error = "No se encontraron reservas o el usuario no existe";
        //    return View(reserva);
        //}

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Details(int id)
        {
            return View();
        }

        public ActionResult Create()
        {
            return View();
        } 

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        

        public ActionResult Edit(int id)
        {
            return View();
        }

          [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }


        public ActionResult Delete(int id)
        {
            return View();
        }


        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }           

    }
}

 stardusthotel/Stardust/Stardust/Views/Pago/Buscar.cshtml
<h2>Buscar Reserva</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validationEngine-en.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validationEngine.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/custom.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.mousewheel.js")" type="text/javascript"></script>

@using (Html.BeginForm("Buscar", "Pago", FormMethod.Post, new { @class = "form" }))
{
    @Html.ValidationSummary(false)
    <fieldset>
        <div class = "widget" >
            <div class = "title"><h6>Buscar Reserva</h6></div>

            <div class="formRow">
                <label>Ingrese el numero de documento</label>
                <div class = "formRight" ><input type = "text" id = "nombre" name = "nombre" /></div>
                <div class = "clear" ></div>
            </div>
        </div>
    </fieldset>
    <p>
        <input type="submit" value="Buscar" class = "redB" />
        @Html.ActionLink("Regresar","../Home/Index")
    </p>
}

 stardusthotel/Stardust/Stardust/Views/Pago/Listar.cshtml
@model List<Stardust.Models.ReservaBean>

<h2>Lista de Reservas</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validationEngine-en.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validationEngine.js")" type="text/javascript"></script>
    
@using (Html.BeginForm("Listar", "Pago", FormMethod.Post, new { @class = "form", id = "validate" }))
{ 
    <p></p><p></p><p></p><p></p>

    <div class="wrapper">
    <div class="widget">
      <div class="title">
      <h6>Lista de Reservas</h6>
      </div>
      <div class="dataTables_wrapper">

        <table cellpadding = "0" cellspacing = "0" border="0" width = "100%" class = "display"> @*cambiar*@
        <thead>
        <tr>
            <th class="ui-state-default" rowspan="1" colspan="1" style="width:160px;">
                <div class="DataTables_sort_wrapper">
                Fecha Llegada
                <span class="DataTables_sort_icon css_right ui-icon ui-icon-triangle-1-s"></span>
                </div>
             </th>
            <th class="ui-state-default" rowspan="1" colspan="1" style="width:160px;" >
                <div class="DataTables_sort_wrapper">
                Fecha Salida
                <span class="DataTables_sort_icon css_right ui-icon ui-icon-triangle-1-s"></span>
                </div>
             </th>
               <th class="ui-state-default" rowspan="1" colspan="1" style="width:120px;" >
                <div class="DataTables_sort_wrapper">
                Pago Inicial
                <span class="DataTables_sort_icon css_right ui-icon ui-icon-triangle-1-s"></span>
                </div>
             </th>
               <th class="ui-state-default" rowspan="1" colspan="1" style="width:120px;" >
                <div class="DataTables_sort_wrapper">
                Monto a Pagar
                <span class="DataTables_sort_icon css_right ui-icon ui-icon-triangle-1-s"></span>
                </div>
             </th>
             <th class="ui-state-default" rowspan="1" colspan="1">

             </th>
        </tr>
    </thead>

        <tbody>
            @for (int i = 0; i < Model.Count; i++)
            {
                @Html.HiddenFor(model => model[i].id)
         
             <tr class="gradeA odd">       
                
                <td>@Html.DisplayFor(model => model[i].fechaRegistro)</td>
                <td>@Html.DisplayFor(model => model[i].fechaCheckOut)</td>
                <td>@Html.DisplayFor(model => model[i].pagoIni)</td>
                <td>@Html.DisplayFor(model => model[i].total)</td>  
                <td>
                    <a href="@Url.Action("PagoHabContado", new { id = Model[i].id })"><img src="../../Content/images/icons/color/cash.png", alt="Cash" />Contado </a> |                    
                    <a href="@Url.Action("PagoHabCredito", new { id = Model[i].id })"><img src="../../Content/images/icons/color/credit.png", alt="Credit" />Credito </a>
                </td>
             </tr>

            }

    
    </tbody>
        </table>

      </div>
        
    </div>
    </div>
    

    <p></p><p></p><p></p><p></p>
    <p>
        <input type="submit" value="Guardar" class = "redB" />
        @Html.ActionLink("Regresar", "../Home/Index")
    </p>
 }

 stardusthotel/Stardust/Stardust/Views/Pago/PagoHabContado.cshtml
@model Stardust.Models.Reserva         
        
<h2>Pago de Habitacion al Contado</h2>
<p></p><p></p><p></p>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validationEngine-en.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validationEngine.js")" type="text/javascript"></script>

 @using (Html.BeginForm("PagoHabContado", "Pago", FormMethod.Post, new { @class = "form", id = "validate"}))
{
    @Html.ValidationSummary(true);
    <div class="title"><h6>Detalle de Reserva</h6> </div>
     <p></p><p></p>
    
        <table cellpadding = "0" cellspacing = "0" width = "100%" class = "sTable" >

    <thead>
        <tr>
            <td>Producto</td>
           <td>Cantidad</td>
           <td>Precio</td>
          
           
        </tr>
    </thead>

    <tbody>

    @Html.HiddenFor(model => model.id) 
  
    @for (int i = 0; (i < Model.listaHab.Count); i++)
    {
             <tr>                      
                <td> @Html.TextBoxFor(model => model.listaHab[i].nombre, new { @readonly = "readonly" }) </td>
                <td> @Html.TextBoxFor(model => model.listaHab[i].cantidad, new { @readonly = "readonly" }) </td>
                <td> @Html.TextBoxFor(model => model.listaHab[i].precio, new { @readonly = "readonly" }) </td>                
            </tr>

    
    }
         
    <tr>
        <td></td>
        <td>Total Sin IGV</td>
        <td>@Html.TextBoxFor(model => model.subTotal, new { @readonly = "readonly" })</td>
    </tr> 

    <tr>
        <td></td>
        <td>IGV</td>
        <td>@Html.TextBoxFor(model => model.igv, new { @readonly = "readonly" })</td>
    </tr>
    
    <tr>
        <td></td>
        <td>Total</td>
        <td>@Html.TextBoxFor(model => model.total, new { @readonly = "readonly" })</td>
    </tr>

    </tbody>

    </table>
     
     <fieldset>

     <div class="formRow">
                @Html.LabelFor(model => model.usuario)
                <div class = "formRight" >@Html.TextBoxFor(model => model.usuario, new { @readonly = "readonly" })</div>
                <div class = "clear" ></div>
    </div>

    <div class="formRow">
                @Html.LabelFor(model => model.hotel)
                <div class = "formRight" >@Html.TextBoxFor(model => model.hotel, new { @readonly = "readonly" })</div>
                <div class = "clear" ></div>
    </div>

    @*<div class="formRow"> Monto a Pagar lo pongo despues :S
                @Html.LabelFor(model => model.)<span class="req">*</span>
                <div class = "formRight" >@Html.TextBoxFor(model => model.pagado1, new { @class = "validate[required,custom[onlyNumberSp]]", name = "numsValid", maxlength = "6", placeholder = "Solo numeros" })</div>
                <div class = "formRight">@ViewBag.error</div>
                <div class = "clear" ></div>
    </div>    *@

    </fieldset>
    <p></p><p></p><p></p><p></p>
    <p>
        <input type="submit" value="Contado" class = "redB"/>        
        @Html.ActionLink("Regresar", "Listar", "Pago")
    </p>
}