 stardusthotel/Stardust/Stardust/Models/Administracion/PerfilUsuario/PerfilUsuarioBean.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace Stardust.Models
{
    public class PerfilUsuarioBean
    {
        [Key]
        public int ID { get; set; }

        [Display(Name = "Nombre")]
        [Required( ErrorMessage = "Debe ingresar un nombre para el perfil de usuario" ) ]
        public string nombre { get; set; }

        [Display(Name = "Descripción")]
        public string descripcion { get; set; }

        public string token { get; set; }
    }
}

 stardusthotel/Stardust/Stardust/Models/Administracion/PerfilUsuario/PerfilUsuarioDAO.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Configuration;
using System.Data.SqlClient;
using log4net;

namespace Stardust.Models
{
    public class PerfilUsuarioDAO
    {
        String cadenaDB = ConfigurationManager.ConnectionStrings["CadenaHotelDB"].ConnectionString;
        private static ILog log = LogManager.GetLogger(typeof(PerfilUsuarioDAO));
        
        public void registrarPerfil(PerfilUsuarioBean perfil) {

            SqlConnection sql = null;
            try
            {
                sql = new SqlConnection(cadenaDB);

                sql.Open();

                String command = "Insert into PerfilUsuario ( nombre , descripcion ) values ('" +
                                perfil.nombre + "', '" +
                                perfil.descripcion + "')";

                SqlCommand query = new SqlCommand(command, sql);
                query.ExecuteNonQuery();

                sql.Close();
            }
            catch (Exception e)
            {
                log.Error("registrarPerfil(EXCEPTION): ", e);
            }
            finally {
                if (sql != null) sql.Close();
            }
        }

        public PerfilUsuarioBean getPerfil( int id ){
            SqlConnection sql = null;
            try
            {
                sql = new SqlConnection(cadenaDB);

                sql.Open();

                String command = "Select * from PerfilUsuario where idPerfilUsuario = " + id;

                SqlCommand query = new SqlCommand(command, sql);
                SqlDataReader data = query.ExecuteReader();

                data.Read();

                PerfilUsuarioBean perfil = new PerfilUsuarioBean();
                perfil.ID = Convert.ToInt32(data["idPerfilUsuario"]);
                perfil.nombre = Convert.ToString(data["nombre"]);
                perfil.descripcion = Convert.ToString(data["descripcion"]);
                perfil.token = Convert.ToString(data["token"]);

                sql.Close();

                return perfil;
            }
            catch (Exception e)
            {
                log.Error("getPerfil(EXCEPTION): ", e);
                throw (e);
            }
            finally {
                if (sql != null) sql.Close();
            }
        }

        public List<PerfilUsuarioBean> listarPerfiles(){
            SqlConnection sql = null;

            try
            {
                sql = new SqlConnection(cadenaDB);

                sql.Open();

                String command = "Select * from PerfilUsuario";

                SqlCommand query = new SqlCommand(command, sql);
                SqlDataReader data = query.ExecuteReader();

                List<PerfilUsuarioBean> lista = new List<PerfilUsuarioBean>();

                while (data.Read())
                {
                    PerfilUsuarioBean perfil = new PerfilUsuarioBean();

                    perfil.ID = Convert.ToInt32(data["idPerfilUsuario"]);
                    perfil.nombre = Convert.ToString(data["nombre"]);
                    perfil.descripcion = Convert.ToString(data["descripcion"]);

                    lista.Add(perfil);
                }

                sql.Close();

                return lista;
            }
            catch (Exception e)
            {
                log.Error("listarPerfiles(EXCEPTION): ", e);
                throw (e);
            }
            finally {
                if (sql != null) sql.Close();
            }
        }

        public List<PerfilUsuarioBean> listarPerfilCliente()
        {
            SqlConnection sql = null;

            try
            {
                sql = new SqlConnection(cadenaDB);

                sql.Open();

                String command = "Select * from PerfilUsuario WHERE nombre = @nombre";

                SqlCommand query = new SqlCommand(command, sql);

                Utils.agregarParametro(query, "nombre", "Cliente");

                SqlDataReader data = query.ExecuteReader();

                List<PerfilUsuarioBean> lista = new List<PerfilUsuarioBean>();

                while (data.Read())
                {
                    PerfilUsuarioBean perfil = new PerfilUsuarioBean();

                    perfil.ID = Convert.ToInt32(data["idPerfilUsuario"]);
                    perfil.nombre = Convert.ToString(data["nombre"]);
                    perfil.descripcion = Convert.ToString(data["descripcion"]);

                    lista.Add(perfil);
                }

                sql.Close();

                return lista;
            }
            catch (Exception e)
            {
                log.Error("listarPerfiles(EXCEPTION): ", e);
                throw (e);
            }
            finally
            {
                if (sql != null) sql.Close();
            }
        }

        public void actualizarPerfil(PerfilUsuarioBean perfil) {
            SqlConnection sql = null;

            try
            {
                sql = new SqlConnection(cadenaDB);

                sql.Open();

                String command = "Update PerfilUsuario SET nombre = '" + perfil.nombre + "', " +
                                 "descripcion = '" + perfil.descripcion + "' where idPerfilUsuario = " + perfil.ID;
                SqlCommand query = new SqlCommand(command, sql);

                query.ExecuteNonQuery();

                sql.Close();
            }
            catch (Exception e)
            {
                log.Error("actualizarPerfil(EXCEPTION): ", e);
            }
            finally {
                if (sql != null) sql.Close();
            }
        }

        public void eliminarPerfil(int id) {
            SqlConnection sql = null;

            try
            {
                sql = new SqlConnection(cadenaDB);

                sql.Open();

                String command = "Delete from PerfilUsuario where idPerfilUsuario = " + id;
                SqlCommand query = new SqlCommand(command, sql);

                query.ExecuteNonQuery();

                sql.Close();
            }
            catch (Exception e)
            {
                log.Error("eliminarPerfil(EXCEPTION): ", e);
            }
            finally {
                if (sql != null) sql.Close();
            }
        }

        public int getPerfilID( string nombre ){
            SqlConnection sql = null ;

            try{
                sql = new SqlConnection( cadenaDB ) ;

                sql.Open();

                String command = "Select * from PerfilUsuario WHERE nombre = @nombre" ;

                SqlCommand query = new SqlCommand( command , sql ) ;

                Utils.agregarParametro( query , "@nombre" , nombre ) ;

                SqlDataReader data =  query.ExecuteReader() ;

                if( data.HasRows ){
                    data.Read() ;
                    return Convert.ToInt32( data[ "idPerfilUsuario" ] ) ;
                }
                return -1 ;
            }catch( Exception e ){
                log.Error( "getPerfilID(EXCEPTION): " , e ) ;
                throw (e);
            }finally{
                if( sql != null ) sql.Close() ;
            }
        }
    }
}

 stardusthotel/Stardust/Stardust/Models/Administracion/PerfilUsuario/PerfilUsuarioFacade.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Stardust.Models
{
    public class PerfilUsuarioFacade
    {
        PerfilUsuarioService perfilServ = new PerfilUsuarioService();

        public void registrarPerfil( PerfilUsuarioBean perfil ){
            perfilServ.registrarPerfil(perfil);
        }

        public List<PerfilUsuarioBean> listarPerfilCliente() {
            return perfilServ.listarPerfilCliente();
        }

        public List<PerfilUsuarioBean> listarPerfiles() {
            return perfilServ.listarPerfiles();
        }

        public PerfilUsuarioBean getPerfil(int id) {
            return perfilServ.getPerfil( id );
        }

        public void actualizarPerfil(PerfilUsuarioBean perfil) {
            perfilServ.actualizarPerfil(perfil);
        }

        public void eliminarPerfil( int id ){
            perfilServ.eliminarPerfil( id );
        }

        public int getPerfilID(string nombre) {
            return perfilServ.getPerfilID(nombre);
        }

    }
}

 stardusthotel/Stardust/Stardust/Models/Administracion/PerfilUsuario/PerfilUsuarioService.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Stardust.Models
{
    public class PerfilUsuarioService
    {
        PerfilUsuarioDAO perfilDAO = new PerfilUsuarioDAO();

        public void registrarPerfil(PerfilUsuarioBean perfil) {
            perfilDAO.registrarPerfil(perfil);
        }

        public List<PerfilUsuarioBean> listarPerfiles() {
            return perfilDAO.listarPerfiles();
        }

        public List<PerfilUsuarioBean> listarPerfilCliente()
        {
            return perfilDAO.listarPerfilCliente();
        }

        public void actualizarPerfil(PerfilUsuarioBean perfil) {
            perfilDAO.actualizarPerfil( perfil );
        }

        public PerfilUsuarioBean getPerfil(int id) {
            return perfilDAO.getPerfil( id ) ;
        }

        public void eliminarPerfil(int id) {
            perfilDAO.eliminarPerfil(id);
        }

        public int getPerfilID(string nombre) {
            return perfilDAO.getPerfilID(nombre);
        }
    }
}

 stardusthotel/Stardust/Stardust/Controllers/Administracion/PerfilUsuarioController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Stardust.Models;

namespace Stardust.Controllers
{ 
    public class PerfilUsuarioController : Controller
    {
        private CadenaHotelDB db = new CadenaHotelDB();
        PerfilUsuarioFacade perfilFac = new PerfilUsuarioFacade();

        //
        // GET: /PerfilUsuario/

        public ViewResult Index()
        {
            return View();
        }

        //
        // GET: /PerfilUsuario/Details/5

        public ViewResult Details(int id)
        {
            try
            {
                return View(perfilFac.getPerfil(id));
            }
            catch {
                return View( new PerfilUsuarioBean() );
            }
        }

        //
        // GET: /PerfilUsuario/Create

        public ActionResult Create()
        {
            return View();
        } 

        //
        // POST: /PerfilUsuario/Create

        [HttpPost]
        public ActionResult Create(PerfilUsuarioBean perfilusuariobean)
        {
            try
            {
                perfilFac.registrarPerfil(perfilusuariobean);
                return RedirectToAction("List");
            }
            catch {
                ViewBag.results = "Ocurrió un error al intentar crear el perfil";
                return View();
            }
        }
        
        //
        // GET: /PerfilUsuario/Edit/5
 
        public ActionResult Edit(int id)
        {
            try
            {
                return View(perfilFac.getPerfil(id));
            }
            catch {
                ViewBag.results = "Ocurrió un error al intentar cargar el perfil";
                return View(new PerfilUsuarioBean());
            }
        }

        //
        // POST: /PerfilUsuario/Edit/5

        [HttpPost]
        public ActionResult Edit(PerfilUsuarioBean perfilusuariobean)
        {
            try
            {
                perfilFac.actualizarPerfil(perfilusuariobean);
                return RedirectToAction("List");
            }
            catch {
                ViewBag.results = "Ocurrió un error al intentar modificar el perfil";
                return View();
            }
        }

        //
        // GET: /PerfilUsuario/Delete/5
 
        public ActionResult Delete(int id)
        {
            try
            {
                return View(perfilFac.getPerfil(id));
            }
            catch {
                ViewBag.results = "Ocurrió un error al intentar cargar el perfil";
                return View(new PerfilUsuarioBean());
            }
        }

        //
        // POST: /PerfilUsuario/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                perfilFac.eliminarPerfil(id);
                return RedirectToAction("List");
            }
            catch {
                ViewBag.results = "Ocurrió un error al intentar eliminar el perfil";
                return View( new PerfilUsuarioBean() );
            }
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }

        public ActionResult List() {
            try
            {
                var model = perfilFac.listarPerfiles();
                return View(model);
            }
            catch {
                ViewBag.results = "Ocurrió un error al intentar listar los perfiles";
                return View(new List<PerfilUsuarioBean>());
            }
        }
    }
}

 stardusthotel/Stardust/Stardust/Views/PerfilUsuario/Create.cshtml
@model Stardust.Models.PerfilUsuarioBean

@{
    ViewBag.Title = "Crear Perfil de Usuario";
}

<h2>Crear perfil de usuario</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@if (!String.IsNullOrEmpty(ViewBag.results)) { 
    <div class="nNote nWarning hideit">
        <p><strong>AVISO: </strong>@ViewBag.results</p>
    </div>
}

@using (Html.BeginForm("Create", "PerfilUsuario", FormMethod.Post, new { @class = "form" } ))
{
    @Html.ValidationSummary(true)
    <fieldset>
        <div class = "widget" >
            <div class = "title" ><h6> Crear Perfil Usuario </h6></div>

            <div class = "formRow" >
                @Html.LabelFor( model => model.nombre )
                <div class = "formRight" >
                    @Html.TextBoxFor( model => model.nombre )
                    @Html.ValidationMessageFor( model => model.nombre ) 
                </div>
                <div class = "clear" ></div>
            </div>

            <div class = "formRow" >
                @Html.LabelFor( model => model.descripcion )
                <div class = "formRight" >
                    @Html.TextBoxFor( model => model.descripcion )
                    @Html.ValidationMessageFor( model => model.descripcion )
                </div>
                <div class = "clear" ></div>
            </div>
        </div>
        <p>
            <input class = "redB" type="submit" value="Crear" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Regresar", "Index")
</div>

 stardusthotel/Stardust/Stardust/Views/PerfilUsuario/Delete.cshtml
@model Stardust.Models.PerfilUsuarioBean

@{
    ViewBag.Title = "Eliminar Perfil";
}

@if (!String.IsNullOrEmpty(ViewBag.results)) { 
    <div class="nNote nWarning hideit">
        <p><strong>AVISO: </strong>@ViewBag.results</p>
    </div>
}

<h2>Borrar perfil</h2>

<h3>Seguro de querer eliminar este perfil?</h3>

<fieldset>
    <div class = "widget" >
        <div class = "title"><h6>Detalles del perfil</h6></div>

        <div class="formRow">
            @Html.LabelFor(model => model.nombre)
            <div class = "formRight" >@Html.DisplayFor(model => model.nombre)</div>
            <div class = "clear" ></div>
        </div>

        <div class="formRow">
            @Html.LabelFor(model => model.descripcion)
            <div class = "formRight" >@Html.DisplayFor(model => model.descripcion)</div>
            <div class = "clear" ></div>
        </div>
    </div>
</fieldset>

@using (Html.BeginForm("Delete", "PerfilUsuario", FormMethod.Post, new { @class = "form" }))
{
    <p>
        <input class = "redB" type="submit" value = "Borrar" /> |
        @Html.ActionLink("Regresar", "List")
    </p>
}

 stardusthotel/Stardust/Stardust/Views/PerfilUsuario/Details.cshtml
@model Stardust.Models.PerfilUsuarioBean

@{
    ViewBag.Title = "Detalles del perfil";
}

@if (!String.IsNullOrEmpty(ViewBag.results)) { 
    <div class="nNote nWarning hideit">
        <p><strong>AVISO: </strong>@ViewBag.results</p>
    </div>
}

<h2>Detalles del perfil</h2>

<fieldset>
    <div class = "widget" >
        <div class = "title"><h6>Detalles del perfil</h6></div>

        <div class="formRow">
            @Html.LabelFor(model => model.nombre)
            <div class = "formRight" >@Html.DisplayFor(model => model.nombre)</div>
            <div class = "clear" ></div>
        </div>

        <div class="formRow">
            @Html.LabelFor(model => model.descripcion)
            <div class = "formRight" >@Html.DisplayFor(model => model.descripcion)</div>
            <div class = "clear" ></div>
        </div>
    </div>
</fieldset>

@using (Html.BeginForm("Edit", "PerfilUsuario", FormMethod.Post, new { @class = "form" }))
{
    <p>
        <a href="@Url.Action("Edit", new { id = Model.ID })"><img src="../../Content/images/icons/color/pencil.png", alt="Edit" />Editar</a> | 
        @Html.ActionLink("Regresar", "List")
    </p>
}

 stardusthotel/Stardust/Stardust/Views/PerfilUsuario/Edit.cshtml
@model Stardust.Models.PerfilUsuarioBean

@{
    ViewBag.Title = "Modificar perfil";
}

<h2>Modificar perfil</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@if (!String.IsNullOrEmpty(ViewBag.results)) { 
    <div class="nNote nWarning hideit">
        <p><strong>AVISO: </strong>@ViewBag.results</p>
    </div>
}

@using (Html.BeginForm("Edit", "PerfilUsuario", FormMethod.Post, new { @class = "form" } ))
{
    @Html.ValidationSummary(true)
    <fieldset>
        <div class = "widget" >
            <div class = "title" ><h6> Modificar Perfil Usuario </h6></div>

            <div class = "formRow" >
                @Html.LabelFor( model => model.nombre )
                <div class = "formRight" >
                    @Html.TextBoxFor( model => model.nombre )
                    @Html.ValidationMessageFor( model => model.nombre ) 
                </div>
                <div class = "clear" ></div>
            </div>

            <div class = "formRow" >
                @Html.LabelFor( model => model.descripcion )
                <div class = "formRight" >
                    @Html.TextBoxFor( model => model.descripcion )
                    @Html.ValidationMessageFor( model => model.descripcion )
                </div>
                <div class = "clear" ></div>
            </div>
        </div>
        <p>
            <input class = "redB" type="submit" value="Guardar" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Regresar", "List")
</div>

 stardusthotel/Stardust/Stardust/Views/PerfilUsuario/Index.cshtml
@model Stardust.Models.PerfilUsuarioBean

@{
    ViewBag.Title = "Perfiles";
}

<h2>Perfiles</h2>

<p>
    Bienvenido a administrar perfiles de usuario.
</p>

<p>
    @Html.ActionLink("Registrar perfil", "Create")
</p>

<p>
    @Html.ActionLink("Listar perfiles", "List")
</p>

 stardusthotel/Stardust/Stardust/Views/PerfilUsuario/List.cshtml
@model IEnumerable<Stardust.Models.PerfilUsuarioBean>

@{
    ViewBag.Title = "Perfiles";
}

@if (!String.IsNullOrEmpty(ViewBag.results)) { 
    <div class="nNote nWarning hideit">
        <p><strong>AVISO: </strong>@ViewBag.results</p>
    </div>
}

<h2>Perfiles</h2>

<p>
    <a href="@Url.Action("Create")"><img src="../../Content/images/icons/color/plus.png", alt="Create" />Añadir perfil</a>
</p>

<table cellpadding = "0" cellspacing = "0" width = "100%" class = "sTable">
    <thead>
        <tr>
            <td>Nombre</td>
            <td>Descripción</td>
            <td></td>
        </tr>
    </thead>

    <tbody>
    @foreach (var item in Model) {
        <tr>
            <td>@Html.DisplayFor(modelItem => item.nombre )</td>
            <td>@Html.DisplayFor(modelItem => item.descripcion )</td>
            <td>
                <a href="@Url.Action("Edit", new { id = item.ID })"><img src="../../Content/images/icons/color/pencil.png", alt="Edit" />Editar </a> | 
                <a href="@Url.Action("Details", new { id = item.ID })"><img src="../../Content/images/icons/color/edit-column.png", alt="Details" />Detalles</a> | 
                <a href="@Url.Action("Delete", new { id = item.ID })"><img src="../../Content/images/icons/color/cross.png", alt="Delete" />Borrar</a>
            </td>
        </tr>
        
    }
    </tbody>
</table>