 stardusthotel/Stardust/Stardust/Models/Compras y Ventas/OrdenCompra/DetalleOrdenCompra.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Stardust.Models
{
    public class DetalleOrdenCompra:ProductoBean
    {
        public int Cantidad { get; set; }
        public int Cantidadentrante { get; set; }
        public decimal precio { get; set; }
        public decimal preciounitario { get; set; }
    }
}

 stardusthotel/Stardust/Stardust/Models/Compras y Ventas/OrdenCompra/NotaEntradaBean.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace Stardust.Models
{
    public class NotaEntradaBean
    {
        public int idordencompra { get; set; }
        public int idhotel { get; set; }
        public int idproveedor { get; set; }
        public int idguiaRemision { get; set; }
        
        [Display(Name = "Proveedor")]
        public string nombreproveedor { get; set; }
        [Display(Name = "hotel")]
        public string nombrehotel { get; set; }
       
        [Display(Name = "Estado")]
        public string estado { get; set; }
        
        [Display(Name = "Fecha")]
        public string fechaemitida{get;set;}
        
        [Display(Name = "Precio Total")]
        public decimal preciototal { get; set; }
        
        [Display(Name = "Fecha")]
        public string fechaRegistradaOrdenCompra { get; set; }

       
        public List<Notaentrada> detallenotaentrada { get; set; }


    }
}

 stardusthotel/Stardust/Stardust/Models/Compras y Ventas/OrdenCompra/Notaentrada.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace Stardust.Models
{
    public class Notaentrada:ProductoBean
    {
        public int cantidadrecibida { get; set; }
        public int cantidadsolicitada { get; set; }
        public int cantidadfaltante { get; set; }
        
        //[Range(0, 999, ErrorMessage = "El número mínimo de días es 1")]
        [RegularExpression("([0-9]+)", ErrorMessage = "Sólo números")]
        [Required(ErrorMessage = "Es necesario ingresar la cantidad entrante")]
        public int cantidadentrante { get; set; }

        public Boolean estado { get; set; }
    }
}

 stardusthotel/Stardust/Stardust/Models/Compras y Ventas/OrdenCompra/OrdenCompraBean.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.Data.SqlClient;
using System.Configuration;
using System.Web.Mvc;

namespace Stardust.Models
{    
    public class Proveedor
    {
        public string ID { get; set; }
        public string Nombre { get; set; }
    }
    
    public class OrdenCompraBean
    {
        public int idOrdenCompra { get; set; }
        public int idproveedor { get; set; }

        public string nombrehotel { get; set; }

        public int idhotel { get; set; }
        
        [Display(Name = "Proveedor")]
        public string idProv { get; set; } 
        
        [Display(Name = "Proveedor")]
        public string nombreproveedor { get; set; }

        [Display(Name = "Producto")]
        public string idProd { get; set; } 
        
        [Display(Name = "Estado")]
        public string estado { get; set; }

        public bool estado2 { get; set; }
        [Display(Name = "Fecha")]
        public string fecha { get; set; }

        [Display(Name = "Precio Total")]
        public decimal preciototal { get; set; }

        public List<Producto> productoList { get; set; }

        public SelectList proveedorList { get; set; }

        public List<DetalleOrdenCompra> detalle { get; set; }
       // List<DetalleOrdenCompra> detalles { get; set; }

        public List<NotaEntradaBean> notasentrada { get; set; }


        public IEnumerable<Proveedor> getProveedor() 
        {
            List<Proveedor> listaProveedor = new List<Proveedor>();

            String cadenaConfiguracion = ConfigurationManager.ConnectionStrings["CadenaHotelDB"].ConnectionString;

            SqlConnection sqlCon = new SqlConnection(cadenaConfiguracion);
            sqlCon.Open();

            string commandString = "SELECT * FROM Proveedor where estado=1";

            SqlCommand sqlCmd = new SqlCommand(commandString, sqlCon);
            SqlDataReader dataReader = sqlCmd.ExecuteReader();

            while (dataReader.Read())
            {
                Proveedor proveedor = new Proveedor();
                proveedor.ID = Convert.ToString(dataReader["idProveedor"]);
                proveedor.Nombre = (string)dataReader["razonSocial"];

                listaProveedor.Add(proveedor);
            }

            return listaProveedor;
        }

        

        public OrdenCompraBean()
        {
            proveedorList = new SelectList(getProveedor(), "ID", "Nombre");
        }


    }
}

 stardusthotel/Stardust/Stardust/Models/Compras y Ventas/OrdenCompra/OrdenCompraService.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Stardust.Models
{
    public class OrdenCompraService
    {
        OrdenCompraDAO ordenCompraDAO = new OrdenCompraDAO();

        public Producto GetProducto(int id)
        {
            return ordenCompraDAO.GetProducto(id);
        }

        public void GuardarOrdenCompra(OrdenProducto producto)
        {
            ordenCompraDAO.GuardarOrdenCompra(producto);
        }
        public List<OrdenCompraBean> getordencompra(string nombre1, string fecha1, string fecha2){
        
            return ordenCompraDAO.getlista(nombre1, fecha1,fecha2);
        }
        public OrdenCompraBean buscarordencompra(int idordenCompra)
        {
            return ordenCompraDAO.buscarordencompra(idordenCompra);
        }

        public void Guardarestadoordencompra(int idorden, string estado)
        {
            ordenCompraDAO.cambiarestado(idorden, estado);
        }
        //notas de entrada

        public List<NotaEntradaBean> listarnotas(int idorden)
        {
            return ordenCompraDAO.ListarNotasEntradas(idorden);
        }
        public void guardarnotaentrada(NotaEntradaBean nota, string estado)
        {
            ordenCompraDAO.GuardarNotaEntrada(nota, estado);
            
        }

        public List<Notaentrada> obtenernotas(int idguiaremision)
        {
            return (ordenCompraDAO.obtenernotas(idguiaremision));
        }

        public void actualizarstock(NotaEntradaBean nota)
        {
            ordenCompraDAO.actualizarstock(nota);
        }
    }
}

 stardusthotel/Stardust/Stardust/Models/Compras y Ventas/OrdenCompra/OrdenProducto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace Stardust.Models
{
    public class OrdenProducto
    {
        [Display(Name = "Proveedor")]
        public string proveedor { get; set; }

        public int id { get; set; } //idproveedor

        public List<Producto> listaProducto { get; set; }
        
        [Display(Name = "IdHotel")]
        public int idhotel { get; set; }

        [Display(Name = "Hotel")]
        public string nombrehotel { get; set; }

        public Boolean estado2 { get; set; }
    }
}

 stardusthotel/Stardust/Stardust/Controllers/Compras y Ventas/OrdenCompraController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Stardust.Models;
using log4net;

namespace Stardust.Controllers
{
    public class OrdenCompraController : Controller
    {
        ComprasFacade comprasFacade = new ComprasFacade();
        ProveedorFacade proveedorFacade = new ProveedorFacade();
        HotelFacade hoteles = new HotelFacade();
        private static ILog log = LogManager.GetLogger(typeof(OrdenCompraController));

        /*--------Orden de Compra----------*/

        public ActionResult Index()
        {
            List<HotelBean> hotel = hoteles.getHoteles();    
            return View(hotel);
        }

        public ActionResult Buscar()
        {
            PagoProveedorBean pagoProveedor = new PagoProveedorBean();
            return View(pagoProveedor);
        }

        [HttpPost]
        public ActionResult Buscar(PagoProveedorBean pago)
        {
            int ID = Convert.ToInt32(pago.ID);
            ProveedorBean prove = proveedorFacade.GetProveedor(ID);
            string nombre = prove.razonSocial;

            return RedirectToAction("Buscar2", new { nombre = nombre });
        }


        public ActionResult Buscar2(string nombre)
        {
            string fecha1 = "";
            string fecha2 = "";

            List<OrdenCompraBean> orden= comprasFacade.buscarOrdenes(nombre, fecha1, fecha2);

            for (int i = 0; i < orden.Count; i++)
            {
                if (orden[i].estado == "Tramite" || orden[i].estado == "Cancelado") orden[i].estado2 = true;
                else orden[i].estado2 = false;
                HotelBean hot = hoteles.getHotel(orden[i].idhotel);
                orden[i].nombrehotel = hot.nombre;
            }

            return View(orden);
        }

        public ActionResult Lista(OrdenCompraBean orden)
        {
            return View(orden);
        }


        public ActionResult Registrar(int id)
        {

            OrdenCompraBean ordenCompra = new OrdenCompraBean();
            ordenCompra.idhotel=id;
            return View(ordenCompra);
        }

        [HttpPost]
        public ActionResult Registrar(OrdenCompraBean ordenCompra)
        {
            int ID = Convert.ToInt32(ordenCompra.idProv);
            return RedirectToAction("Registrar2", new { id = ID,idhotel=ordenCompra.idhotel});
        }

        public ViewResult Registrar2(int id, int idhotel) //registrar orden compra.......idproveedor y id hotel
        {
            OrdenProducto prod = new OrdenProducto();
            ProveedorBean prov = proveedorFacade.GetProveedor(id);

            int cantidad = 0;
            ProductoxProveedorBean productosprov = proveedorFacade.obtenerlista(id); // de la tabla productoxpreoveedor
            int idalmacen = comprasFacade.obteneralmacen(idhotel);
            ProductoXAlmacenBean productosalmacen = comprasFacade.obtenerlistadAlmacen(idalmacen); // de la tabla productoxalmacen


            List<Producto> produ = new List<Producto>();

            for (int i = 0; i < productosalmacen.listProdalmacen.Count; i++)
            {
                for (int j = 0; j < productosprov.listProdProv.Count; j++)
                {
                    if (productosalmacen.listProdalmacen[i].ID == productosprov.listProdProv[j].ID)
                    {
                        Producto produc = new Producto();
                        produc.idproducto = productosalmacen.listProdalmacen[i].ID;
                        produc.Nombre = proveedorFacade.GetNombreProducto(productosalmacen.listProdalmacen[i].ID);
                        produc.precio = productosprov.listProdProv[j].precio;
                        produc.stockActual = productosalmacen.listProdalmacen[i].stockactual;
                        produc.stockMinimo = productosalmacen.listProdalmacen[i].stockminimo;
                        produc.stockMaximo = productosalmacen.listProdalmacen[i].stockmaximo;
                        if (produc.stockActual <= produc.stockMinimo) { produc.estado = true; cantidad++; }
                        else { produc.estado = false; }
                        produ.Add(produc);
                    }
                    
                }
            }
            
            prod.listaProducto = produ;
            prod.proveedor = prov.razonSocial;
            prod.id = id;//idproveedor
            prod.idhotel = idhotel;
            HotelBean hotel = hoteles.getHotel(idhotel);
            prod.nombrehotel = hotel.nombre;

            //Boolean est = prod.listaProducto[0].estado;
            if (cantidad > 0) prod.estado2 = true; else prod.estado2 = false;
            return View(prod);
        }

        [HttpPost]    
        public ActionResult Registrar2(OrdenProducto producto)
        {
            

            for (int i = 0; i < producto.listaProducto.Count; i++)
            {
                if (producto.listaProducto[i].cantidad > 0)
                {
                    producto.listaProducto[i].estadoguardar = true;
                   
                }
                else
                {
                    producto.listaProducto[i].estadoguardar = false;
                }
            }

            comprasFacade.GuardarOrdenCompra(producto);
            return RedirectToAction("Buscar");
        }

        public ActionResult DetalleOrdenC(int id) //id orden compra
        {
            OrdenCompraBean ordencompra = comprasFacade.buscarOrdenes(id);
            ProveedorBean proveedor = proveedorFacade.GetProveedor(ordencompra.idproveedor);
            ordencompra.nombreproveedor = proveedor.razonSocial;

            for (int i = 0; i < ordencompra.detalle.Count; i++)
            {
                ProductoBean produc = proveedorFacade.Getproducto(ordencompra.detalle[i].ID);
                ordencompra.detalle[i].nombre = produc.nombre;
            }
            ProductoxProveedorBean productos = proveedorFacade.obtenerlista(ordencompra.idproveedor);
            for (int i = 0; i < ordencompra.detalle.Count; i++)
            {
                for (int j = 0; j < productos.listProdProv.Count; j++)
                {
                    if (ordencompra.detalle[i].ID == productos.listProdProv[j].ID)
                    {
                        ordencompra.detalle[i].preciounitario = productos.listProdProv[j].precio;
                    }
                }
            }

            List<NotaEntradaBean> notas = comprasFacade.listarnotasentrada(id);
            for (int i = 0; i < notas.Count; i++)
            {
                int idguiaremision = notas[i].idguiaRemision;
                List<Notaentrada> not2 = comprasFacade.obtenernotas(idguiaremision);
                for (int j=0; j < not2.Count; j++)
                {
                    for (int k = 0; k < ordencompra.detalle.Count(); k++)
                    {
                        if (ordencompra.detalle[k].ID == not2[j].ID)
                        {
                            ordencompra.detalle[k].Cantidadentrante+=not2[j].cantidadrecibida;
                        }
                    }
                }
            }
            
            HotelBean hot= hoteles.getHotel(ordencompra.idhotel);
            ordencompra.nombrehotel = hot.nombre;
            return View(ordencompra);
        }

        public ActionResult ModificarOrdenC(int id) //idordencompra
        {
            OrdenCompraBean ordencompra = comprasFacade.buscarOrdenes(id);
            ProveedorBean proveedor = proveedorFacade.GetProveedor(ordencompra.idproveedor);
            ordencompra.nombreproveedor = proveedor.razonSocial;

            for (int i = 0; i < ordencompra.detalle.Count; i++)
            {
                ProductoBean produc = proveedorFacade.Getproducto(ordencompra.detalle[i].ID);
                ordencompra.detalle[i].nombre = produc.nombre;
            }
            ProductoxProveedorBean productos = proveedorFacade.obtenerlista(ordencompra.idproveedor);
            for (int i = 0; i < ordencompra.detalle.Count; i++)
            {
                for (int j = 0; j < productos.listProdProv.Count; j++)
                {
                    if (ordencompra.detalle[i].ID == productos.listProdProv[j].ID)
                    {
                        ordencompra.detalle[i].preciounitario =  productos.listProdProv[j].precio;
                    }
                }
            }
            HotelBean hot = hoteles.getHotel(ordencompra.idhotel);
            ordencompra.nombrehotel = hot.nombre;
            return View(ordencompra);

        }


        public ActionResult GuardarestadoOrdenC(OrdenCompraBean orden) 
        {
            // guarda el estado de la orden de compra a registrado o cancelado
            comprasFacade.modificarestadoordencompra(orden.idOrdenCompra, orden.estado);
            return RedirectToAction("Buscar");
        }
        /*--------Notas de Entrada----------*/

        public ActionResult ListarNotaEntrada(int id) 
        {
            List<NotaEntradaBean> notas = comprasFacade.listarnotasentrada(id);//idordencompra

            OrdenCompraBean ordencompra = comprasFacade.buscarOrdenes(id);
            ordencompra.notasentrada = new List<NotaEntradaBean>();
            
            for (int i = 0; i < notas.Count; i++)
            {
                ordencompra.notasentrada.Add(notas[i]);
            }
            
            ProveedorBean proveedor = proveedorFacade.GetProveedor(ordencompra.idproveedor);
            ordencompra.nombreproveedor = proveedor.razonSocial;
            HotelBean hot= hoteles.getHotel(ordencompra.idhotel);
            ordencompra.nombrehotel = hot.nombre;
            return View(ordencompra);
        }


 stardusthotel/Stardust/Stardust/Views/OrdenCompra/Buscar.cshtml

@model Stardust.Models.PagoProveedorBean

@{
    ViewBag.Title = "Buscar Orden compra";
}

<h2>Buscar Orden Compra</h2>

@using (Html.BeginForm("Buscar", "Ordencompra", FormMethod.Post, new { @class = "form" }))
{
    @Html.ValidationSummary(false)
    <fieldset>
        <div class = "widget" >
            <div class = "title">
                <h6>Seleccionar Proveedor</h6>
            </div>

            <div class="formRow">
                <label>Proveedor</label>
                <div class = "formRight" >@Html.DropDownListFor(model => model.ID,Model.proveedorList)</div>
                <div class = "clear" ></div>
            </div>
        </div>
    </fieldset>
    <p>
        <input type="submit" value="Buscar" class = "redB" />
    </p>
}


 stardusthotel/Stardust/Stardust/Views/OrdenCompra/DetalleOrdenC.cshtml
@model Stardust.Models.OrdenCompraBean

@{
    ViewBag.Title = "Detalle del Orden Compra";
}

<h2>Proveedor</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

    
@using (Html.BeginForm("ModificarOrdenC/"+ Model.idOrdenCompra, "OrdenCompra", FormMethod.Post, new { @class = "form" }))
{
   
    
    <fieldset>
        <div class="widget">
            <div class="title">
                <h6>Detalle de La Orden Compra</h6> @Html.HiddenFor(model => model.idhotel)
            </div>
            <div class="formRow"> @Html.LabelFor(model => model.nombrehotel)
                <div class=" formRight"> @Html.DisplayFor(model => model.nombrehotel)  @Html.HiddenFor(model => model.nombrehotel) </div>
                <div class="clear"></div>
            </div>
            <div class="formRow"> @Html.LabelFor(model => model.nombreproveedor)
                <div class=" formRight"> @Html.DisplayFor(model => model.nombreproveedor)  @Html.HiddenFor(model => model.nombreproveedor) </div>
                <div class="clear"></div>
            </div>
            <div class="formRow">@Html.LabelFor(model => model.fecha)
                <div class="formRight"> @Html.DisplayFor(model => model.fecha) @Html.HiddenFor(model => model.fecha) </div>
                <div class="clear"></div>
            </div>

            <div class="formRow">@Html.LabelFor(model => model.estado)
                <div class="formRight"> @Html.DisplayFor(model => model.estado)  @Html.HiddenFor(model => model.estado) </div>
                <div class="clear"></div>
            </div>
          
            
        </div>
    </fieldset>
    
    
    <div class="widget">

          <div class="title"><img src="../../Content/images/icons/dark/frames.png" alt="" class="titleIcon" /><h6>Lista de Productos Solicitados</h6></div>

            <table cellpadding="0" cellspacing="0" width="100%" class="sTable">

                <thead>
                    <tr>
                        <td>Producto</td>
                        <td>Cantidad Pedida</td>
                        <td>Cantidad Entrante</td>
                        <td>Precio Unitario</td>
                        <td>Precio Total</td>
                    </tr>
                </thead>

                <tbody>
                        @for (int i = 0; i < Model.detalle.Count; i++)
                        {
                    <tr>       
                            @Html.HiddenFor(model => model.detalle[i].ID);
                        <td> @Html.DisplayFor(model => model.detalle[i].nombre) @Html.HiddenFor(model => model.detalle[i].nombre) </td>
                        <td> @Html.DisplayFor(model => model.detalle[i].Cantidad) @Html.HiddenFor(model => model.detalle[i].Cantidad)</td>
                        <td> @Html.DisplayFor(model => model.detalle[i].Cantidadentrante)  @Html.HiddenFor(model => model.detalle[i].Cantidadentrante)</td>
                        <td style=" text-align:right"> @Html.DisplayFor(model => model.detalle[i].preciounitario) @Html.HiddenFor(model => model.detalle[i].preciounitario)</td>
                        <td style=" text-align:right"> @Html.DisplayFor(model => model.detalle[i].precio) @Html.HiddenFor(model => model.detalle[i].precio)</td>
                      
                    </tr>       
                        }

                    <tr>
                        <td></td>
                        <td></td> 
                        <td></td> 
                        <td>Monto Total</td>
                        <td style=" text-align:right" > @Html.DisplayFor(model => model.preciototal) @Html.HiddenFor(model => model.preciototal)</td>
                    </tr>
                </tbody>

            </table>

      </div>

   @* <p>
        <input type="submit" value="Editar" class = "redB" />
    </p>
    *@
    <p>
       
       <a href="javascript:window.history.back();">Regresar</a>
    </p>
    
}
       

 stardusthotel/Stardust/Stardust/Views/OrdenCompra/DetallenotaEntrada.cshtml
@model Stardust.Models.NotaEntradaBean

@{
    ViewBag.Title = "Detalle Nota Entrada";
}

<h2>Detalle de La Orden Compra</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>


    
@using (Html.BeginForm("ListarNotaEntrada", "OrdenCompra", FormMethod.Post, new { @class = "form" }))
{
   @Html.ValidationSummary(false)
    
    <fieldset>
        <div class="widget">
            <div class="title">
                <h6>Detalle de La Orden Compra</h6>
            </div>
            <div class="formRow"> @Html.LabelFor(model => model.nombreproveedor)<span class="req">*</span>
                <div class=" formRight"> @Html.DisplayFor(model => model.nombreproveedor)  </div>
                <div class="clear"></div>
            </div>
            <div class="formRow"> @Html.LabelFor(model => model.nombrehotel)<span class="req">*</span>
                <div class=" formRight"> @Html.DisplayFor(model => model.nombrehotel)  </div>
                <div class="clear"></div>
            </div>
            <div class="formRow">@Html.LabelFor(model => model.fechaemitida)<span class="req">*</span>
                <div class="formRight"> @Html.DisplayFor(model => model.fechaemitida) </div>
                <div class="clear"></div>
            </div>
            
        </div>
    </fieldset>
    
    
    <div class="widget">

          <div class="title"><img src="../../Content/images/icons/dark/frames.png" alt="" class="titleIcon" /><h6>Lista de Productos</h6></div>

            <table cellpadding="0" cellspacing="0" width="100%" class="sTable">

                <thead>
                    <tr>
                        <td>Producto</td>
                        <td>Cantidad Recibida</td>

                    </tr>
                </thead>

                <tbody>
                        @for (int i = 0; i < Model.detallenotaentrada.Count; i++)
                        {
                    <tr>       
               
                        <td> @Html.DisplayFor(model => model.detallenotaentrada[i].nombre) @Html.HiddenFor(model => model.detallenotaentrada[i].nombre) </td>
                        <td> @Html.DisplayFor(model => model.detallenotaentrada[i].cantidadrecibida) @Html.HiddenFor(model => model.detallenotaentrada[i].nombre) </td>

                      
                    </tr>       
                        }


                </tbody>

            </table>

      </div>

    
    <p>
       
        @Html.ActionLink("Regresar", "ListarNotaEntrada/" + Model.idordencompra, "OrdenCompra")
    </p>
    
}
       

 stardusthotel/Stardust/Stardust/Views/OrdenCompra/ListarNotaEntrada.cshtml
@model Stardust.Models.OrdenCompraBean

@{
    ViewBag.Title = "Listado de notas de Entrada";
}

<h2>Nota de Entrada</h2>
<p></p><p></p><p></p>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

 
 @using (Html.BeginForm("", "OrdenCompra", FormMethod.Post, new { @class = "form" }))
 { 
    <fieldset>
        <div class="widget">
            <div class="title">
                <h6>Notas de Entrada</h6>
            </div>
            <div class="formRow"> @Html.LabelFor(model => model.nombreproveedor)
                <div class=" formRight">  @Html.DisplayFor(model => model.nombreproveedor) @Html.HiddenFor(model => model.nombreproveedor) </div>
                <div class="clear"></div>
            </div>
             <div class="formRow"> @Html.LabelFor(model => model.nombrehotel)
                <div class=" formRight">  @Html.DisplayFor(model => model.nombrehotel) @Html.HiddenFor(model => model.nombrehotel) </div>
                <div class="clear"></div>
            </div>
            
            <div class="formRow"> @Html.LabelFor(model => model.fecha)
                <div class=" formRight">  @Html.DisplayFor(model => model.fecha) @Html.HiddenFor(model => model.fecha)  </div>
                <div class="clear"></div>
            </div>
            
        </div>
    </fieldset>
    
    <p>
    <a href="@Url.Action("RegistrarNotaEntrada", new { id = Model.idOrdenCompra })"><img src="../../Content/images/icons/color/plus.png", alt="Create" />Registrar Nota entrada</a>
    </p>
    <p></p><p></p><p></p><p></p>

    <div class="title"><h6>Notas de entrada que tiene la Orden de Compra</h6> </div>
     <p></p><p></p>
    
        <table cellpadding = "0" cellspacing = "0" width = "100%" class = "sTable" >

    <thead>
        <tr>
            <td>IdNotaentrada</td>
            <td>Fecha Emitida</td>
            <td>Opciones</td>
        </tr>
    </thead>

    <tbody>
    

        @for (int i = 0; (i < Model.notasentrada.Count); i++)
        {
    <tr>       
               
                <td> @Html.DisplayFor(model => model.notasentrada[i].idguiaRemision)  @Html.HiddenFor(model => model.notasentrada[i].idguiaRemision)</td>
                <td> @Html.DisplayFor(model => model.notasentrada[i].fechaemitida) @Html.HiddenFor(model => model.notasentrada[i].fechaemitida)</td>
                <td><a href="@Url.Action("DetallenotaEntrada", new { id = Model.notasentrada[i].idguiaRemision, id2=Model.idOrdenCompra })"><img src="../../Content/images/icons/color/pencil.png", alt="Edit" />Detalle </a></td>
               
     </tr>

    
        }

           
    </tbody>

    </table>
    <p></p><p></p><p></p><p></p>
    <p>
        <a href="javascript:window.history.back();">Regresar</a>
    </p>

 }

 stardusthotel/Stardust/Stardust/Views/OrdenCompra/Registrar.cshtml
@model Stardust.Models.OrdenCompraBean

<h2>Registrar Orden de Compra</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>


@using (Html.BeginForm("Registrar", "OrdenCompra", FormMethod.Post, new { @class = "form" }))
{
    @Html.ValidationSummary(false)
    <fieldset>
            <div class="widget">
            <div class="title">
                <h6>Seleccionar Proveedor</h6>
            </div>
            @Html.HiddenFor(model => model.idhotel)
            <div class="formRow">
               @Html.LabelFor(model => model.idProv)                              
                
                <div class = "formRight" >
                <div class = "selector">@Html.DropDownListFor(model => model.idProv, Model.proveedorList)</div></div>
                <div class = "clear" ></div>
            </div>

            </div>
            
    </fieldset>
            <p></p> <p></p> <p></p>
    <div>
           <input type="submit" value="Seleccionar" class = "redB" /> |
           @Html.ActionLink("Regresar", "Index")
    </div>
}